language: python

python:
  - '3.7-dev'

services: postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

install:
  - pip install pipenv
  - pipenv install --deploy

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
