language: python

python:
  - '3.7-dev'

services: postgresql

install:
  - pip install pipenv
  - pipenv install --deploy

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py test
