# Generated by Django 2.1.5 on 2019-01-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(null=True, to='core.Company'),
        ),
    ]
