# Generated by Django 2.1.5 on 2019-01-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(blank=True, to='core.Company'),
        ),
    ]
